# Problem Statement: **Welcome to AI Town!**

### You’ve been hired as an AI engineer in **AI Town**, a futuristic city powered by artificial intelligence. Your job is to use PyTorch to solve foundational challenges that AI Town faces. Each task requires you to demonstrate your expertise with PyTorch basics.



---



Imports and CUDA

In [1]:
import torch

# Check if CUDA (GPU) is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")


Using device: cuda




---



**Task1: Inventory Management**

AI Town’s warehouse uses sensors to record the inventory of 5 items every day. Each day’s data is represented as a list of integers (number of units).

In [2]:
#1 Create a PyTorch Tensor from the following inventory data
inventory = torch.tensor([
    [12, 15, 10, 0, 5],
    [10, 8, 7, 5, 4],
    [20, 10, 15, 5, 2]
])

In [5]:
#2 Find the total inventory for each item across all days
total_inventory = inventory.sum(dim=0)
total_inventory

tensor([42, 33, 32, 10, 11])

In [60]:
#3 Find the average inventory per day
inventory.float().mean(dim=1)

tensor([ 8.4000,  6.8000, 10.4000])



---



**Task2: Monitoring Vehicle Flow**

AI Town uses a sensor to monitor the number of vehicles passing through two main roads every hour. The data for one day (24 hours) is represented as two
1×24 tensors.

In [13]:
#1 Simulate this data using PyTorch's Random Functions

vehicle_sensor1 = torch.randint(0, 100, (24,), device=device, dtype=torch.int16)
vehicle_sensor2 = torch.randint(0, 100, (24,), device=device, dtype=torch.int16)
vehicle_sensor1, vehicle_sensor2

(tensor([61,  1, 95, 88, 31, 84, 76, 23, 66, 21, 22, 57, 53, 62,  0, 59, 32, 58,
         37, 59, 21, 97, 88, 24], device='cuda:0', dtype=torch.int16),
 tensor([68, 89, 61, 42,  4, 72, 55, 58, 84, 39,  4,  3, 82, 46, 83, 28, 85, 51,
         97, 13, 61, 47, 25, 43], device='cuda:0', dtype=torch.int16))

In [15]:
#2 Write the function to calculate the total vehicle flow for each road across the entire day
vehicle_flow1 = vehicle_sensor1.sum()
vehicle_flow2 = vehicle_sensor2.sum()
vehicle_flow1, vehicle_flow2

(tensor(1215, device='cuda:0'), tensor(1240, device='cuda:0'))

In [16]:
#3 Write the function to calculate the total vehicle flow for each hour across both roads
vehicle_sensor1 + vehicle_sensor2

tensor([129,  90, 156, 130,  35, 156, 131,  81, 150,  60,  26,  60, 135, 108,
         83,  87, 117, 109, 134,  72,  82, 144, 113,  67], device='cuda:0',
       dtype=torch.int16)



---



**Task3: Fitness Matrix**

The AI Gym tracks members’ fitness scores using a 3×3 matrix for *strength*, *stamina*, and f*lexibility*. Each row represents a different member, and each column represents a specific metric.

In [64]:
#1 Create a 3*3 tensor matrix and multiply the scores of each member by a weight factor: [0.8, 1.2, 1.5]


gym = torch.randint(0, 10, (3,3), dtype=torch.int16)
weights = torch.tensor([0.8, 1.2, 1.5])
weighted_fitness = weights * gym
print(weighted_fitness)

tensor([[ 2.4000,  2.4000, 10.5000],
        [ 0.8000,  7.2000, 12.0000],
        [ 1.6000,  9.6000,  9.0000]])


In [65]:
#2 Find the row-wise and column-wise maximum scores
row_max = torch.max(weighted_fitness, dim=1)[0]
col_max = torch.max(weighted_fitness, dim=0)[0]
row_max, col_max

(tensor([10.5000, 12.0000,  9.6000]), tensor([ 2.4000,  9.6000, 12.0000]))

In [66]:
#3 Transpose the fitness matrix and interpret it's new structure (shape)
weighted_fitness.t()

tensor([[ 2.4000,  0.8000,  1.6000],
        [ 2.4000,  7.2000,  9.6000],
        [10.5000, 12.0000,  9.0000]])



---



**Task4: Chain Rule in Action**

AI Lab is running experiments to understand the effect of temperature (
x) on a chemical reaction rate (y). The relationship is given as:
$y = 2x^3 + 5x^2 - 3x + 7$



In [31]:
#1 Use PyTorch to compute 'y' for x = 4
x = torch.tensor(4, requires_grad=True, dtype=torch.float16)
y = 2*x**3 + 5*x**2 - 3*x + 7
y

tensor(203., dtype=torch.float16, grad_fn=<AddBackward0>)

In [32]:
#2 Calculate dy/dx(gradient) using PyTorch's autograd
y.backward()

x.grad

tensor(133., dtype=torch.float16)



---



**Task5: Camera Calibration**

AI Town’s surveillance cameras need to align their focus. You are given the following matrices for two cameras’ focus adjustments:

In [44]:
camera1 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
camera2 = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

In [45]:
#1 Perform an element-wise multiplication of matrices ( Hadamard Product)
camera1 * camera2

tensor([[ 5., 12.],
        [21., 32.]])

In [46]:
#2 Compute Dot Product of the two matrices
torch.matmul(camera1, camera2)

tensor([[19., 22.],
        [43., 50.]])

In [47]:
#3 Compute the Determinant of each matrix
torch.det(camera1), torch.det(camera2)

(tensor(-2.), tensor(-2.0000))



---



**Task6: Neural Network Foundations**

Our AI University uses simplified single neuron model (perceptron):
$$y = wx + b$$

In [55]:
#1 Create tensors for w  = 2, b = 1, x = [1, 2, 3, 4]

w = torch.tensor(2)
b = torch.tensor(1)
x = torch.tensor([1, 2, 3, 4])

In [56]:
#2 Compute tensors for y
y = w*x + b
y

tensor([3, 5, 7, 9])



---

