In [1]:
import torch

In [2]:
torch.tensor(9)

tensor(9)

In [3]:
revenue = torch.tensor([100, 120, 90, 75])
revenue

tensor([100, 120,  90,  75])

In [4]:
# Sales data for Quarter 1 (Matrix 1)
#Rows represent different products, columns represent different regions
q1= torch.tensor ([
    [200, 220, 250], # Product A (iPhone) 
    [150, 180, 210], # Product B (iPad)
    [300, 330, 360], # Product C (MacBook)
    ])

q2= torch.tensor([ 
    [209, 231, 259], # Product A (iPhone)
    [155, 192, 222], # Product B (iPad) 
    [310, 340, 375], # Product C (MacBook)
])

In [5]:
q1 + q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [6]:
q2 - q1

tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [7]:
# profit per unit is given product and region wise
# calculate total profit for all units per region, per product 
profit_per_unit = torch.tensor([
    [30,27,25],
    [20,18,17], 
    [45,38,39],
])

In [8]:
profit_per_unit * q1

tensor([[ 6000,  5940,  6250],
        [ 3000,  3240,  3570],
        [13500, 12540, 14040]])

In [9]:
product_prices = torch.tensor([1100, 450, 1500])
product_prices

tensor([1100,  450, 1500])

In [10]:
torch.matmul(product_prices, q1)

tensor([737500, 818000, 909500])

In [13]:
torch.t(product_prices)

tensor([1100,  450, 1500])

In [17]:
q1 * product_prices.unsqueeze(1).reshape(3,1)

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [19]:
prices_by_region = q1 * product_prices.unsqueeze(1).reshape(3,1)
prices_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [21]:
prices_by_region.sum(dim=0)

tensor([737500, 818000, 909500])

In [22]:
# Create portfolio composition matrix (3x3)
# Rows: Different portfolios (P1, P2, P3)
# Columns: Asset allocation (Stocks, Bonds, Real Estate) 
portfolio_composition = torch.tensor([
    [100.0, 50.0, 30.0], # P1
    [80.0, 70.0, 20.0],  # P2
    [60.0, 40.0, 90.0],  # P3
], dtype=torch.float32)

# Create price change matrix (3x3)
# Rows: Assets (Stocks, Bonds, Real Estate)
# Columns: Economic scenarios (Growth, Neutral, Recession) 
price_changes = torch.tensor([
    [1.15, 1.05, 0.85], # Stocks
    [1.05, 1.02, 1.10], # Bonds
    [1.10, 1.00, 0.90]  # Real Estate
], dtype=torch.float32)

values = torch.matmul(portfolio_composition, price_changes)
values

tensor([[200.5000, 186.0000, 167.0000],
        [187.5000, 175.4000, 163.0000],
        [210.0000, 193.8000, 176.0000]])

In [25]:
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

In [26]:
device.type

'cuda'

In [27]:
# Simluating customer data with 1 million customers and 3 features (age, spending score, income)
customer_data = torch.rand(1_000_000, 3, device=device)
customer_data.shape

torch.Size([1000000, 3])

In [28]:
customer_data[:5]

tensor([[0.5081, 0.6907, 0.5661],
        [0.5071, 0.9890, 0.0256],
        [0.9540, 0.6401, 0.4172],
        [0.6583, 0.3145, 0.1636],
        [0.3162, 0.2451, 0.7174]], device='cuda:0')

In [31]:
customer_data[:, 1] > 0.5

tensor([ True,  True,  True,  ..., False, False, False], device='cuda:0')

In [33]:
high_spending_customers = customer_data[customer_data[:, 1] > 0.5]
high_spending_customers

tensor([[0.5081, 0.6907, 0.5661],
        [0.5071, 0.9890, 0.0256],
        [0.9540, 0.6401, 0.4172],
        ...,
        [0.1390, 0.7010, 0.8920],
        [0.4173, 0.8868, 0.8823],
        [0.2756, 0.6270, 0.7633]], device='cuda:0')

In [34]:
high_spending_customers.shape

torch.Size([499797, 3])

In [35]:
high_spending_customers.to('cpu')

tensor([[0.5081, 0.6907, 0.5661],
        [0.5071, 0.9890, 0.0256],
        [0.9540, 0.6401, 0.4172],
        ...,
        [0.1390, 0.7010, 0.8920],
        [0.4173, 0.8868, 0.8823],
        [0.2756, 0.6270, 0.7633]])

In [36]:
units = torch.tensor([
    [200, 220], # Product A (iPhone)
    [150, 180], # Product B (iPad) 
    [300, 330], # Product C (MacBook)
])

In [37]:
units.shape

torch.Size([3, 2])

In [38]:
units.dtype

torch.int64

In [39]:
units.device

device(type='cpu')

In [40]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330])

In [41]:
units.view(2,3)

tensor([[200, 220, 150],
        [180, 300, 330]])

In [44]:
units[2, 1] = 389
units

tensor([[200, 220],
        [150, 180],
        [300, 389]])

In [ ]:
torch.rand(3, 4)